# Form implementation generated from reading ui file './assets/settings.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(580, 401)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(settingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hidLabel = QtWidgets.QLabel(parent=settingsDialog)
        self.hidLabel.setObjectName("hidLabel")
        self.horizontalLayout.addWidget(self.hidLabel)
        self.hidText = QtWidgets.QLineEdit(parent=settingsDialog)
        self.hidText.setObjectName("hidText")
        self.horizontalLayout.addWidget(self.hidText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.devconLabel = QtWidgets.QLabel(parent=settingsDialog)
        self.devconLabel.setEnabled(False)
        self.devconLabel.setObjectName("devconLabel")
        self.horizontalLayout_2.addWidget(self.devconLabel)
        self.devconText = QtWidgets.QLineEdit(parent=settingsDialog)
        self.devconText.setEnabled(False)
        self.devconText.setObjectName("devconText")
        self.horizontalLayout_2.addWidget(self.devconText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(parent=settingsDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveBtn = QtWidgets.QPushButton(parent=settingsDialog)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_3.addWidget(self.saveBtn)
        self.resetBtn = QtWidgets.QPushButton(parent=settingsDialog)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_3.addWidget(self.resetBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(settingsDialog)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Settings"))
        self.hidLabel.setText(_translate("settingsDialog", "HID driver name"))
        self.devconLabel.setText(_translate("settingsDialog", "Devcon exe path"))
        self.saveBtn.setText(_translate("settingsDialog", "Save and Exit"))
        self.resetBtn.setText(_translate("settingsDialog", "Reset"))
