# Form implementation generated from reading ui file './assets/settings.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(348, 245)
        self.widget = QtWidgets.QWidget(parent=settingsDialog)
        self.widget.setGeometry(QtCore.QRect(30, 23, 291, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hidLabel = QtWidgets.QLabel(parent=self.widget)
        self.hidLabel.setObjectName("hidLabel")
        self.horizontalLayout.addWidget(self.hidLabel)
        self.hidText = QtWidgets.QLineEdit(parent=self.widget)
        self.hidText.setObjectName("hidText")
        self.horizontalLayout.addWidget(self.hidText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.devconLabel = QtWidgets.QLabel(parent=self.widget)
        self.devconLabel.setEnabled(False)
        self.devconLabel.setObjectName("devconLabel")
        self.horizontalLayout_2.addWidget(self.devconLabel)
        self.devconText = QtWidgets.QLineEdit(parent=self.widget)
        self.devconText.setEnabled(False)
        self.devconText.setObjectName("devconText")
        self.horizontalLayout_2.addWidget(self.devconText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveBtn = QtWidgets.QPushButton(parent=self.widget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_3.addWidget(self.saveBtn)
        self.resetBtn = QtWidgets.QPushButton(parent=self.widget)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_3.addWidget(self.resetBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(settingsDialog)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Dialog"))
        self.hidLabel.setText(_translate("settingsDialog", "HID driver name"))
        self.devconLabel.setText(_translate("settingsDialog", "Devcon exe path"))
        self.saveBtn.setText(_translate("settingsDialog", "Save and Exit"))
        self.resetBtn.setText(_translate("settingsDialog", "Reset"))
